### ISSUE TITLE
Request to Capture and Store User Details as an Array.

### ISSUE THREAD

**Issue by Ananyasingh2002** [Ananyasingh2002/OTP-Verification#1]
**Hacktoberfest-Accepted** 👍

**Issue Overview:**

I'm currently working on a Flask application, and I have a requirement to store the details entered by the user and print them as an array within the Flask application. Here's an overview of what I'm trying to achieve:

**Requirements:**
- Users enter various details on a web form, including name, prn, email, branch, and phone number.
- I want to capture these details for each user and store them in an array.
- After capturing the details, I would like to print the user data as an array within my Flask application.

**Objective:**
This would allow me to keep a record of all the user details submitted through the application.

**Additional Information:**
- I'm currently using Flask, and I'm looking for guidance or a solution on how to implement this feature effectively.

**Acceptance Criteria:**
- The user details should be captured and stored as an array.
- The stored data should be printable within the Flask application.

Your assistance and suggestions in achieving this objective would be greatly appreciated. Thank you!

**Comment by harshkushwaha2001** [comment]
hi @Ananyasingh2002 I would like work on this issue, 
please assign me.

**Comment by Manav39** [comment]
Hey @Ananyasingh2002 , I would like to contribute to this issue. Please assign this issue me

**Comment by Ananyasingh2002** [comment]
Yes @Manav39 , feel free to make changes.
